name: Sync with Iosevka Releases

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch Latest Iosevka Release
        id: fetch-iosevka
        run: |
          latest_iosevka_release=$(curl -s https://api.github.com/repos/be5invis/Iosevka/releases/latest | jq -r .tag_name)
          echo "latest_iosevka_release=$latest_iosevka_release" >> $GITHUB_ENV

      - name: Check for Corresponding Millennium Code Release
        id: check-release
        run: |
          response=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases)
          if echo "$response" | jq -e --arg tag "${{ env.latest_iosevka_release }}" '.[] | select(.tag_name == $tag)' > /dev/null; then
            echo "Corresponding Millennium Code release found: ${{ env.latest_iosevka_release }}"
            echo "release_exists=true" >> $GITHUB_ENV
          else
            echo "No corresponding Millennium Code release found for Iosevka release ${{ env.latest_iosevka_release }}"
            echo "release_exists=false" >> $GITHUB_ENV

      - name: Trigger Build Workflow
        if: env.release_exists == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                release: process.env.latest_iosevka_release
              }
            })

      - name: Create Millennium Code Release
        if: env.release_exists == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.latest_iosevka_release,
              name: `Millennium Code ${process.env.latest_iosevka_release}`,
              body: `This release matches [Iosevka release ${process.env.latest_iosevka_release}](https://github.com/be5invis/Iosevka/releases/tag/${process.env.latest_iosevka_release}).`,
              draft: false,
              prerelease: false
            })
